### ISSUE TITLE
The Application "Remix" Can't be opened after download

### ISSUE THREAD

**Issue by ChangyuYan** [ethereum/remix-desktop#116]
I downloaded  Remix-IDE-1.3.3-mac.zip for my mac (12.0.1), and when I unzip it and try to open it, it says "can't be opened" without giving me any other reasons. Help, please?

**Comment by ch13fd357r0y3r** [comment]
Go to settings and search for security and privacy. Choose "General" and tick the check box for Remix IDE under "Allow apps downloaded from"

**Comment by seungjun-green** [comment]
Having the same issue, I certainly did allow Apps downloaded from App Store and identified developers but can't open the app.

**Comment by web3dopamine** [comment]
same here, cannot open

**Comment by yann300** [comment]
the latest release should fix that - https://github.com/ethereum/remix-desktop/releases - sorry for the delay.
Please make sure to reopen if the issue persists.

**Comment by gunjan316** [comment]
Im still facing the same issue while I do allow Apps downloaded from App Store and identified developers but can't open the app.
