### ISSUE TITLE
White screen on windows 10.

### ISSUE THREAD

**Issue by LALauw** [ethereum/remix-desktop#120]
I can't open Remix IDE on my desktop anymore. All I get is a white screen upon launch and in the dev tools it shows this error:
![image](https://user-images.githubusercontent.com/32265116/163575355-2ff72b36-0c36-41ed-a61a-3859805201a3.png)

I downgraded to 1.3.2 but same issue when on 1.3.3
![image](https://user-images.githubusercontent.com/32265116/163575403-7364a62f-3337-41c1-aacf-d9d2ad425355.png)

**Comment by q1n9-jair** [comment]
+1

**Comment by KostiantynLogunovValtech** [comment]
I have the same issue on the desktop version(( only white screen

**Comment by nghiemlong** [comment]
Same for new, either latest for penultimate versions. :(. No error, but empty blank screen.

**Comment by C-m3-Codin** [comment]
on changing the fetch url in loader the issue can be fixed 
![issue](https://user-images.githubusercontent.com/39019726/163660602-2d88b359-598c-4795-89cb-4e08b1a28bfb.png)
once I changed the function and ran it on console the IDE loaded fine
![change](https://user-images.githubusercontent.com/39019726/163660619-1b076dac-e651-44e5-b16a-1411912eca51.png)

**Comment by snussik** [comment]
@C-m3-Codin 
> or paste this function in the console...

causes errors.

Use instead:
```js
fetch('https://remix.ethereum.org/assets/version.json', { cache: "no-store" }).then(response => {
  response.text().then(function (data) {
    const version = JSON.parse(data);
    console.log(`Loading Remix ${version.version}`);
    createScriptTag(`polyfills.${version.version}.${version.timestamp}.js`, 'module');
    if (version.mode === 'development') {
      createScriptTag(`vendor.${version.version}.${version.timestamp}.js`, 'module');
      createScriptTag(`runtime.${version.version}.${version.timestamp}.js`, 'module');
    }
    createScriptTag(`main.${version.version}.${version.timestamp}.js`, 'text/javascript');
  });
});
```

**Comment by q1n9-jair** [comment]
> @C-m3-Codin
> 
> > 或将此功能粘贴到控制台中...
> 
> 导致错误。
> 
> 改用：
> 
> ```js
> 获取（'https://remix.ethereum.org/assets/version.json' ， { 缓存：“no-store”  } ）。then ( response  =  > { 
>   response.text ( ) . then ( function ( data ) { const version = JSON.parse ( data ) ; console.log ( ` Loading Remix $ { version.version } ` _ _ _ _  
>        
>     ) ; 
>     createScriptTag ( `polyfills. $ { version.version } . $ { version.timestamp } .js` , '  module ' ) ; 
>     if  ( version .mode === 'development' ) { createScriptTag  ( `vendor . $ { version.version } . $ { version.timestamp } .js` , ' module ' ) ; createScriptTag  
>        
>       ( `runtime. $ { version.version } . $ { version.timestamp } .js` , '  module ' ) ; 
>     } 
>     createScriptTag （`main. $ { version.version } . $ { version.timestamp } .js` , '  text /javascript' ）；
>   } ) ; 
> } ) ;
> ```

![image](https://user-images.githubusercontent.com/38864807/163669140-2236842a-0157-4cdd-8ce8-c76d4958d839.png)
It's still useless

**Comment by nghiemlong** [comment]
Pls tell me where is the loader.js file. I only found Remix IDE\resources\app\node_modules\js-yaml\lib\js-yaml\loader.js

**Comment by JavaConterry** [comment]
Ctrl+Sift+I
paste it into console:

fetch('https://remix.ethereum.org/assets/version.json', { cache: "no-store" }).then(response => { 
	response.text().then(function (data) {
		const version = JSON.parse(data); 
		console.log(`Loading Remix ${version.version}`); 	
		createScriptTag(`polyfills.${version.version}.${version.timestamp}.js`, 'module'); 
		if (version.mode === 'development') { 
			createScriptTag(`vendor.${version.version}.${version.timestamp}.js`, 'module');
			createScriptTag(`runtime.${version.version}.${version.timestamp}.js`, 'module'); 
		} 
		createScriptTag(`main.${version.version}.${version.timestamp}.js`, 'text/javascript'); 
	}); 
});
fetch('assets/version.json', { cache: "no-store" }).then(response => {
  response.text().then(function (data) {
    const version = JSON.parse(data);
    console.log(`Loading Remix ${version.version}`);
    createScriptTag(`polyfills.${version.version}.${version.timestamp}.js`, 'module');
    if (version.mode === 'development') {
      createScriptTag(`vendor.${version.version}.${version.timestamp}.js`, 'module');
      createScriptTag(`runtime.${version.version}.${version.timestamp}.js`, 'module');
    }
    createScriptTag(`main.${version.version}.${version.timestamp}.js`, 'text/javascript');
  });
});

**Comment by LALauw** [comment]
> @C-m3-Codin
> 
> > or paste this function in the console...
> 
> causes errors.
> 
> Use instead:
> 
> ```js
> fetch('https://remix.ethereum.org/assets/version.json', { cache: "no-store" }).then(response => {
>   response.text().then(function (data) {
>     const version = JSON.parse(data);
>     console.log(`Loading Remix ${version.version}`);
>     createScriptTag(`polyfills.${version.version}.${version.timestamp}.js`, 'module');
>     if (version.mode === 'development') {
>       createScriptTag(`vendor.${version.version}.${version.timestamp}.js`, 'module');
>       createScriptTag(`runtime.${version.version}.${version.timestamp}.js`, 'module');
>     }
>     createScriptTag(`main.${version.version}.${version.timestamp}.js`, 'text/javascript');
>   });
> });
> ```

This worked perfectly for me, thanks!

**Comment by q1n9-jair** [comment]
> Loading Remix ${version.version}

hello bro Have you solved it？

**Comment by C-m3-Codin** [comment]
fetch('https://remix.ethereum.org/assets/version.json', { cache: "no-store" }).then(response => {
  response.text().then(function (data) {
    const version = JSON.parse(data);
    console.log(`Loading Remix ${version.version}`);
    createScriptTag(`polyfills.${version.version}.${version.timestamp}.js`, 'module');
    if (version.mode === 'development') {
      createScriptTag(`vendor.${version.version}.${version.timestamp}.js`, 'module');
      createScriptTag(`runtime.${version.version}.${version.timestamp}.js`, 'module');
    }
    createScriptTag(`main.${version.version}.${version.timestamp}.js`, 'text/javascript');
  });
});
Just past this in the console 
press CTRL+SHIFT+I to open console

**Comment by cyberkarma** [comment]
zsh: parse error near `}' then i try to run this command on mac terminal

**Comment by C-m3-Codin** [comment]
not terminal 
open console from Remix IDE
for MAC
open Remix
COMMAND + OPTIONS + i
select console 
paste the code.

**Comment by q1n9-jair** [comment]
https://user-images.githubusercontent.com/38864807/163718095-816bd8b6-052c-41df-842d-5454f1ed1041.mp4

Why can't mine?

**Comment by C-m3-Codin** [comment]
Not in the sources select the 

> Desktop.2022.04.17.-.22.07.28.04.DVR.mp4 
> Why can't mine?

Not in the sources select the  console tab and do the same .

**Comment by q1n9-jair** [comment]
> Not in the sources select the
> 
> > Desktop.2022.04.17.-.22.07.28.04.DVR.mp4
> > Why can't mine?
> 
> Not in the sources select the console tab and do the same .

hello  Where is that?

**Comment by C-m3-Codin** [comment]
![IMG-20220417-WA0014](https://user-images.githubusercontent.com/39019726/163721040-9f1e6833-78cf-4a79-a2af-32a887b30010.jpg)

**Comment by q1n9-jair** [comment]
> ![IMG-20220417-WA0014](https://user-images.githubusercontent.com/39019726/163721040-9f1e6833-78cf-4a79-a2af-32a887b30010.jpg)

thank you

Finally ok

**Comment by keeplook** [comment]
> not terminal open console from Remix IDE for MAC open Remix COMMAND + OPTIONS + i select console paste the code.

每次打开都要执行一次吗

**Comment by keeplook** [comment]
> not terminal open console from Remix IDE for MAC open Remix COMMAND + OPTIONS + i select console paste the code.

Do I have to execute it once every time I open it

**Comment by cwli24** [comment]
Nope, tried all these. RIP.
![image](https://user-images.githubusercontent.com/28714891/163924880-eb8eba0e-7ee5-43ad-942a-8df390b28c3f.png)

**Comment by dovgopoly** [comment]
> Nope, tried all these. RIP. ![image](https://user-images.githubusercontent.com/28714891/163924880-eb8eba0e-7ee5-43ad-942a-8df390b28c3f.png)

same

**Comment by CodeCmn** [comment]
![image](https://user-images.githubusercontent.com/59222436/164357812-b5ce15c3-c771-4a63-9740-17bd78477d40.png)

**Comment by xSevithx** [comment]
Same issue here, None of the above fixed worked either.

**Comment by StungInDaBut** [comment]
Running an intel Mac, no solutions here work either

**Comment by PhantomYdn** [comment]
Same issue. Awaiting Devs. Seems that new version of Chrome broke something for Remix.

**Comment by kaxaru** [comment]
I wrote a temporary solution in another thread. I hope it helps

let createScriptTag = function(url, type) {
var script = document.createElement('script');
script.src = url;
script.type = type;
document.getElementsByTagName('head')[0].appendChild(script);
}

let type = 'text/javascript'
let files = [
'https://remix.ethereum.org/vendors~app.0.23.1.1650320458854.js', 'https://remix.ethereum.org/app.0.23.1.1650320458854.js', 'https://remix.ethereum.org/polyfills.0.23.1.1650320458854.js', 'https://remix.ethereum.org/main.0.23.1.1650320458854.js', 'https://remix.ethereum.org/raw-loader!-ethersproject-abi-lib-index-d-ts.0.23.1.1650320458854.js',
'https://remix.ethereum.org/raw-loader!-ethersproject-abstract-provider-lib-index-d-ts.0.23.1.1650320458854.js',
'https://remix.ethereum.org/raw-loader!-ethersproject-abstract-signer-lib-index-d-ts.0.23.1.1650320458854.js',
'https://remix.ethereum.org/raw-loader!-ethersproject-address-lib-index-d-ts.0.23.1.1650320458854.js',
'https://remix.ethereum.org/raw-loader!-ethersproject-base64-lib-index-d-ts.0.23.1.1650320458854.js',
'https://remix.ethereum.org/raw-loader!-ethersproject-basex-lib-index-d-ts.0.23.1.1650320458854.js',
'https://remix.ethereum.org/raw-loader!-ethersproject-bignumber-lib-index-d-ts.0.23.1.1650320458854.js',
'https://remix.ethereum.org/raw-loader!-ethersproject-bytes-lib-index-d-ts.0.23.1.1650320458854.js',
'https://remix.ethereum.org/raw-loader!-ethersproject-constants-lib-index-d-ts.0.23.1.1650320458854.js',
'https://remix.ethereum.org/raw-loader!-ethersproject-contracts-lib-index-d-ts.0.23.1.1650320458854.js',
'https://remix.ethereum.org/raw-loader!-ethersproject-hash-lib-index-d-ts.0.23.1.1650320458854.js',
'https://remix.ethereum.org/raw-loader!-ethersproject-hdnode-lib-index-d-ts.0.23.1.1650320458854.js',
'https://remix.ethereum.org/raw-loader!-ethersproject-json-wallets-lib-index-d-ts.0.23.1.1650320458854.js',
'https://remix.ethereum.org/raw-loader!-ethersproject-keccak256-lib-index-d-ts.0.23.1.1650320458854.js',
'https://remix.ethereum.org/raw-loader!-ethersproject-logger-lib-index-d-ts.0.23.1.1650320458854.js',
'https://remix.ethereum.org/raw-loader!-ethersproject-networks-lib-index-d-ts.0.23.1.1650320458854.js',
'https://remix.ethereum.org/raw-loader!-ethersproject-pbkdf2-lib-index-d-ts.0.23.1.1650320458854.js',
'https://remix.ethereum.org/raw-loader!-ethersproject-properties-lib-index-d-ts.0.23.1.1650320458854.js',
'https://remix.ethereum.org/raw-loader!-ethersproject-providers-lib-index-d-ts.0.23.1.1650320458854.js',
'https://remix.ethereum.org/raw-loader!-ethersproject-random-lib-index-d-ts.0.23.1.1650320458854.js',
'https://remix.ethereum.org/raw-loader!-ethersproject-rlp-lib-index-d-ts.0.23.1.1650320458854.js',
'https://remix.ethereum.org/raw-loader!-ethersproject-sha2-lib-index-d-ts.0.23.1.1650320458854.js',
'https://remix.ethereum.org/raw-loader!-ethersproject-signing-key-lib-index-d-ts.0.23.1.1650320458854.js',
'https://remix.ethereum.org/raw-loader!-ethersproject-solidity-lib-index-d-ts.0.23.1.1650320458854.js',
'https://remix.ethereum.org/raw-loader!-ethersproject-strings-lib-index-d-ts.0.23.1.1650320458854.js',
'https://remix.ethereum.org/raw-loader!-ethersproject-transactions-lib-index-d-ts.0.23.1.1650320458854.js',
'https://remix.ethereum.org/raw-loader!-ethersproject-units-lib-index-d-ts.0.23.1.1650320458854.js',
'https://remix.ethereum.org/raw-loader!-ethersproject-wallet-lib-index-d-ts.0.23.1.1650320458854.js',
'https://remix.ethereum.org/raw-loader!-ethersproject-web-lib-index-d-ts.0.23.1.1650320458854.js',
'https://remix.ethereum.org/raw-loader!-ethersproject-wordlists-lib-index-d-ts.0.23.1.1650320458854.js',
'https://remix.ethereum.org/raw-loader!ethers-lib-ethers-d-ts.0.23.1.1650320458854.js',
'https://remix.ethereum.org/raw-loader!ethers-lib-index-d-ts.0.23.1.1650320458854.js',
'https://remix.ethereum.org/raw-loader!web3-bzz-types-index-d-ts.0.23.1.1650320458854.js',
'https://remix.ethereum.org/raw-loader!web3-core-types-index-d-ts.0.23.1.1650320458854.js',
'https://remix.ethereum.org/raw-loader!web3-eth-personal-types-index-d-ts.0.23.1.1650320458854.js',
'https://remix.ethereum.org/raw-loader!web3-eth-types-index-d-ts.0.23.1.1650320458854.js',
'https://remix.ethereum.org/raw-loader!web3-net-types-index-d-ts.0.23.1.1650320458854.js',
'https://remix.ethereum.org/raw-loader!web3-shh-types-index-d-ts.0.23.1.1650320458854.js',
'https://remix.ethereum.org/raw-loader!web3-types-index-d-ts.0.23.1.1650320458854.js',
'https://remix.ethereum.org/raw-loader!web3-utils-types-index-d-ts.0.23.1.1650320458854.js'
]

files.forEach(f => createScriptTag(f, type))

**Comment by lytves** [comment]
> I wrote a temporary solution in another thread. I hope it helps
> 
> let createScriptTag = function(url, type) { var script = document.createElement('script'); script.src = url; script.type = type; document.getElementsByTagName('head')[0].appendChild(script); }
> 
> ......

This helped to me! Thanks a lot!

**Comment by lytves** [comment]
> I wrote a temporary solution in another thread. I hope it helps
> 
> let createScriptTag = function(url, type) { var script = document.createElement('script'); script.src = url; script.type = type; document.getElementsByTagName('head')[0].appendChild(script); }
> 
> ......

This helped to me! Thanks a lot!

**Comment by cwli24** [comment]
Looks like it was some server-sided script misconfiguration. This issue has been fixed for me naturally, so I guess the problem is resolved? Can anyone else verify the fix?

**Comment by andrey-sh** [comment]
> Looks like it was some server-sided script misconfiguration. This issue has been fixed for me naturally, so I guess the problem is resolved? Can anyone else verify the fix?

On macos seems fixed

**Comment by pixkk** [comment]
I was helped by installing the previous version, on which everything worked. Then I updated to the latest version.

**Comment by yann300** [comment]
The latest release should fix that:
https://github.com/ethereum/remix-desktop/releases
please reopen if the issue is still persisting
