### ISSUE TITLE
White screen on Mac OS 12

### ISSUE THREAD

**Issue by LifeOfPunk** [ethereum/remix-desktop#121]

**Comment by andrey-sh** [comment]
same

**Comment by C-m3-Codin** [comment]
#120 
proposed solution worked
https://github.com/ethereum/remix-desktop/issues/120#issuecomment-1100559670

**Comment by cyberkarma** [comment]
how to open console on remix macos desctop?

> C-m3-Codin

**Comment by C-m3-Codin** [comment]
> how to open console on remix macos desctop?
> 
> > C-m3-Codin
CMD + OPTION+I  on MAC
CTRL + SHIFT + I on windows

Then 
1.select console 
2.paste the code from above

**Comment by LifeOfPunk** [comment]
> #120 proposed solution worked [#120 (comment)](https://github.com/ethereum/remix-desktop/issues/120#issuecomment-1100559670)

it works, thank you mate!

**Comment by yann300** [comment]
The latest release should fix that:
https://github.com/ethereum/remix-desktop/releases
please reopen if the issue is still persisting
