### ISSUE TITLE
White Screen on Remix Desktop IDE

### ISSUE THREAD

**Issue by naziakhan123** [ethereum/remix-desktop#122]
![image](https://user-images.githubusercontent.com/103852722/163688019-4406e34b-1ed0-47f8-ae74-6bd64165931d.png)
Remix desktop ide is stuck on white screen not working properly please resolve the issue

**Comment by KostiantynLogunovValtech** [comment]
I have the same problem( on windows

**Comment by saqoah** [comment]
```
fetch('https://remix.ethereum.org/assets/version.json', { cache: "no-store" }).then(response => {
  response.text().then(function (data) {
    const version = JSON.parse(data);
    console.log(`Loading Remix ${version.version}`);
    createScriptTag(`polyfills.${version.version}.${version.timestamp}.js`, 'module');
    if (version.mode === 'development') {
      createScriptTag(`vendor.${version.version}.${version.timestamp}.js`, 'module');
      createScriptTag(`runtime.${version.version}.${version.timestamp}.js`, 'module');
    }
    createScriptTag(`main.${version.version}.${version.timestamp}.js`, 'text/javascript');
  });
});
```

press CTRL+SHIFT+I to open console
Just past this in the console

**Comment by ValeriyIvanov** [comment]
> ```
> fetch('https://remix.ethereum.org/assets/version.json', { cache: "no-store" }).then(response => {
>   response.text().then(function (data) {
>     const version = JSON.parse(data);
>     console.log(`Loading Remix ${version.version}`);
>     createScriptTag(`polyfills.${version.version}.${version.timestamp}.js`, 'module');
>     if (version.mode === 'development') {
>       createScriptTag(`vendor.${version.version}.${version.timestamp}.js`, 'module');
>       createScriptTag(`runtime.${version.version}.${version.timestamp}.js`, 'module');
>     }
>     createScriptTag(`main.${version.version}.${version.timestamp}.js`, 'text/javascript');
>   });
> });
> ```
> 
> press CTRL+SHIFT+I to open console Just past this in the console

for mac pls

**Comment by chimera0garden** [comment]
> > ```
> > fetch('https://remix.ethereum.org/assets/version.json', { cache: "no-store" }).then(response => {
> >   response.text().then(function (data) {
> >     const version = JSON.parse(data);
> >     console.log(`Loading Remix ${version.version}`);
> >     createScriptTag(`polyfills.${version.version}.${version.timestamp}.js`, 'module');
> >     if (version.mode === 'development') {
> >       createScriptTag(`vendor.${version.version}.${version.timestamp}.js`, 'module');
> >       createScriptTag(`runtime.${version.version}.${version.timestamp}.js`, 'module');
> >     }
> >     createScriptTag(`main.${version.version}.${version.timestamp}.js`, 'text/javascript');
> >   });
> > });
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > press CTRL+SHIFT+I to open console Just past this in the console
> 
> 
> for mac pls

Press command + option + I when the remix IDE is open and paste the above code in the 'console'. Press enter and let it run

**Comment by ValeriyIvanov** [comment]
Loading Remix 0.23.1
loader.js:26 GET package://6fd22d6fe5549ad4c4d8fd3ca0b7816b.mod/main.0.23.1.1650320458854.js net::ERR_NOT_IMPLEMENTED
createScriptTag @ loader.js:26
(anonymous) @ VM278:10
Promise.then (async)
(anonymous) @ VM278:2
Promise.then (async)
(anonymous) @ VM278:1

**Comment by Innovoeb** [comment]
Code snippets above no longer working

```
GET package://6fd22d6fe5549ad4c4d8fd3ca0b7816b.mod/main.0.23.1.1650320458854.js net::ERR_NOT_IMPLEMENTED

```

**Comment by minichris** [comment]
also is happening to me

**Comment by insurshawn** [comment]
Happening also to me.

**Comment by mirageN1349** [comment]
It's still an ongoing issue.

**Comment by xSevithx** [comment]
Is there a fix to this? All of the fixes mentioned do not work.

**Comment by xSevithx** [comment]
![image](https://user-images.githubusercontent.com/8484294/164530647-bd844079-ec63-4c5c-aefb-815be722b49a.png)

**Comment by FinnishArmy** [comment]
I've even tried installed an older version but it causes a javascript error when opening. None of the mentioned 'fixes' do anything and only cause errors.

**Comment by kaxaru** [comment]
Today I put in an IDE and got a white screen too. Assets on the snippet above are not loaded either. I compared the scripts load on the desktop version and the online version. And fixed it like this

let createScriptTag = function(url, type) {
    var script = document.createElement('script');
    script.src = url;
    script.type = type;
    document.getElementsByTagName('head')[0].appendChild(script);
}

let type = 'text/javascript'
let files = [
'https://remix.ethereum.org/vendors~app.0.23.1.1650320458854.js', 'https://remix.ethereum.org/app.0.23.1.1650320458854.js', 'https://remix.ethereum.org/polyfills.0.23.1.1650320458854.js', 'https://remix.ethereum.org/main.0.23.1.1650320458854.js', 'https://remix.ethereum.org/raw-loader!-ethersproject-abi-lib-index-d-ts.0.23.1.1650320458854.js',
'https://remix.ethereum.org/raw-loader!-ethersproject-abstract-provider-lib-index-d-ts.0.23.1.1650320458854.js',
'https://remix.ethereum.org/raw-loader!-ethersproject-abstract-signer-lib-index-d-ts.0.23.1.1650320458854.js',
'https://remix.ethereum.org/raw-loader!-ethersproject-address-lib-index-d-ts.0.23.1.1650320458854.js',
'https://remix.ethereum.org/raw-loader!-ethersproject-base64-lib-index-d-ts.0.23.1.1650320458854.js',
'https://remix.ethereum.org/raw-loader!-ethersproject-basex-lib-index-d-ts.0.23.1.1650320458854.js',
'https://remix.ethereum.org/raw-loader!-ethersproject-bignumber-lib-index-d-ts.0.23.1.1650320458854.js',
'https://remix.ethereum.org/raw-loader!-ethersproject-bytes-lib-index-d-ts.0.23.1.1650320458854.js',
'https://remix.ethereum.org/raw-loader!-ethersproject-constants-lib-index-d-ts.0.23.1.1650320458854.js',
'https://remix.ethereum.org/raw-loader!-ethersproject-contracts-lib-index-d-ts.0.23.1.1650320458854.js',
'https://remix.ethereum.org/raw-loader!-ethersproject-hash-lib-index-d-ts.0.23.1.1650320458854.js',
'https://remix.ethereum.org/raw-loader!-ethersproject-hdnode-lib-index-d-ts.0.23.1.1650320458854.js',
'https://remix.ethereum.org/raw-loader!-ethersproject-json-wallets-lib-index-d-ts.0.23.1.1650320458854.js',
'https://remix.ethereum.org/raw-loader!-ethersproject-keccak256-lib-index-d-ts.0.23.1.1650320458854.js',
'https://remix.ethereum.org/raw-loader!-ethersproject-logger-lib-index-d-ts.0.23.1.1650320458854.js',
'https://remix.ethereum.org/raw-loader!-ethersproject-networks-lib-index-d-ts.0.23.1.1650320458854.js',
'https://remix.ethereum.org/raw-loader!-ethersproject-pbkdf2-lib-index-d-ts.0.23.1.1650320458854.js',
'https://remix.ethereum.org/raw-loader!-ethersproject-properties-lib-index-d-ts.0.23.1.1650320458854.js',
'https://remix.ethereum.org/raw-loader!-ethersproject-providers-lib-index-d-ts.0.23.1.1650320458854.js',
'https://remix.ethereum.org/raw-loader!-ethersproject-random-lib-index-d-ts.0.23.1.1650320458854.js',
'https://remix.ethereum.org/raw-loader!-ethersproject-rlp-lib-index-d-ts.0.23.1.1650320458854.js',
'https://remix.ethereum.org/raw-loader!-ethersproject-sha2-lib-index-d-ts.0.23.1.1650320458854.js',
'https://remix.ethereum.org/raw-loader!-ethersproject-signing-key-lib-index-d-ts.0.23.1.1650320458854.js',
'https://remix.ethereum.org/raw-loader!-ethersproject-solidity-lib-index-d-ts.0.23.1.1650320458854.js',
'https://remix.ethereum.org/raw-loader!-ethersproject-strings-lib-index-d-ts.0.23.1.1650320458854.js',
'https://remix.ethereum.org/raw-loader!-ethersproject-transactions-lib-index-d-ts.0.23.1.1650320458854.js',
'https://remix.ethereum.org/raw-loader!-ethersproject-units-lib-index-d-ts.0.23.1.1650320458854.js',
'https://remix.ethereum.org/raw-loader!-ethersproject-wallet-lib-index-d-ts.0.23.1.1650320458854.js',
'https://remix.ethereum.org/raw-loader!-ethersproject-web-lib-index-d-ts.0.23.1.1650320458854.js',
'https://remix.ethereum.org/raw-loader!-ethersproject-wordlists-lib-index-d-ts.0.23.1.1650320458854.js',
'https://remix.ethereum.org/raw-loader!ethers-lib-ethers-d-ts.0.23.1.1650320458854.js',
'https://remix.ethereum.org/raw-loader!ethers-lib-index-d-ts.0.23.1.1650320458854.js',
'https://remix.ethereum.org/raw-loader!web3-bzz-types-index-d-ts.0.23.1.1650320458854.js',
'https://remix.ethereum.org/raw-loader!web3-core-types-index-d-ts.0.23.1.1650320458854.js',
'https://remix.ethereum.org/raw-loader!web3-eth-personal-types-index-d-ts.0.23.1.1650320458854.js',
'https://remix.ethereum.org/raw-loader!web3-eth-types-index-d-ts.0.23.1.1650320458854.js',
'https://remix.ethereum.org/raw-loader!web3-net-types-index-d-ts.0.23.1.1650320458854.js',
'https://remix.ethereum.org/raw-loader!web3-shh-types-index-d-ts.0.23.1.1650320458854.js',
'https://remix.ethereum.org/raw-loader!web3-types-index-d-ts.0.23.1.1650320458854.js',
'https://remix.ethereum.org/raw-loader!web3-utils-types-index-d-ts.0.23.1.1650320458854.js'
]

files.forEach(f => createScriptTag(f, type))

**Comment by dhood** [comment]
Hi, this was my first time trying to use Remix and I thought my development was blocked by this white screen, but actually no! For others who didn't know, there's the https://remix.ethereum.org browser version that you can use while this gets addressed (the Gitter chat says they're working on a fix though :+1: 🙇 ). Hope that helps!

**Comment by KursatCAKAL** [comment]
> Today I put in an IDE and got a white screen too. Assets on the snippet above are not loaded either. I compared the scripts load on the desktop version and the online version. And fixed it like this
> 
> let createScriptTag = function(url, type) { var script = document.createElement('script'); script.src = url; script.type = type; document.getElementsByTagName('head')[0].appendChild(script); }
> 
> let type = 'text/javascript' let files = [ 'https://remix.ethereum.org/vendors~app.0.23.1.1650320458854.js', 'https://remix.ethereum.org/app.0.23.1.1650320458854.js', 'https://remix.ethereum.org/polyfills.0.23.1.1650320458854.js', 'https://remix.ethereum.org/main.0.23.1.1650320458854.js', 'https://remix.ethereum.org/raw-loader!-ethersproject-abi-lib-index-d-ts.0.23.1.1650320458854.js', 'https://remix.ethereum.org/raw-loader!-ethersproject-abstract-provider-lib-index-d-ts.0.23.1.1650320458854.js', 'https://remix.ethereum.org/raw-loader!-ethersproject-abstract-signer-lib-index-d-ts.0.23.1.1650320458854.js', 'https://remix.ethereum.org/raw-loader!-ethersproject-address-lib-index-d-ts.0.23.1.1650320458854.js', 'https://remix.ethereum.org/raw-loader!-ethersproject-base64-lib-index-d-ts.0.23.1.1650320458854.js', 'https://remix.ethereum.org/raw-loader!-ethersproject-basex-lib-index-d-ts.0.23.1.1650320458854.js', 'https://remix.ethereum.org/raw-loader!-ethersproject-bignumber-lib-index-d-ts.0.23.1.1650320458854.js', 'https://remix.ethereum.org/raw-loader!-ethersproject-bytes-lib-index-d-ts.0.23.1.1650320458854.js', 'https://remix.ethereum.org/raw-loader!-ethersproject-constants-lib-index-d-ts.0.23.1.1650320458854.js', 'https://remix.ethereum.org/raw-loader!-ethersproject-contracts-lib-index-d-ts.0.23.1.1650320458854.js', 'https://remix.ethereum.org/raw-loader!-ethersproject-hash-lib-index-d-ts.0.23.1.1650320458854.js', 'https://remix.ethereum.org/raw-loader!-ethersproject-hdnode-lib-index-d-ts.0.23.1.1650320458854.js', 'https://remix.ethereum.org/raw-loader!-ethersproject-json-wallets-lib-index-d-ts.0.23.1.1650320458854.js', 'https://remix.ethereum.org/raw-loader!-ethersproject-keccak256-lib-index-d-ts.0.23.1.1650320458854.js', 'https://remix.ethereum.org/raw-loader!-ethersproject-logger-lib-index-d-ts.0.23.1.1650320458854.js', 'https://remix.ethereum.org/raw-loader!-ethersproject-networks-lib-index-d-ts.0.23.1.1650320458854.js', 'https://remix.ethereum.org/raw-loader!-ethersproject-pbkdf2-lib-index-d-ts.0.23.1.1650320458854.js', 'https://remix.ethereum.org/raw-loader!-ethersproject-properties-lib-index-d-ts.0.23.1.1650320458854.js', 'https://remix.ethereum.org/raw-loader!-ethersproject-providers-lib-index-d-ts.0.23.1.1650320458854.js', 'https://remix.ethereum.org/raw-loader!-ethersproject-random-lib-index-d-ts.0.23.1.1650320458854.js', 'https://remix.ethereum.org/raw-loader!-ethersproject-rlp-lib-index-d-ts.0.23.1.1650320458854.js', 'https://remix.ethereum.org/raw-loader!-ethersproject-sha2-lib-index-d-ts.0.23.1.1650320458854.js', 'https://remix.ethereum.org/raw-loader!-ethersproject-signing-key-lib-index-d-ts.0.23.1.1650320458854.js', 'https://remix.ethereum.org/raw-loader!-ethersproject-solidity-lib-index-d-ts.0.23.1.1650320458854.js', 'https://remix.ethereum.org/raw-loader!-ethersproject-strings-lib-index-d-ts.0.23.1.1650320458854.js', 'https://remix.ethereum.org/raw-loader!-ethersproject-transactions-lib-index-d-ts.0.23.1.1650320458854.js', 'https://remix.ethereum.org/raw-loader!-ethersproject-units-lib-index-d-ts.0.23.1.1650320458854.js', 'https://remix.ethereum.org/raw-loader!-ethersproject-wallet-lib-index-d-ts.0.23.1.1650320458854.js', 'https://remix.ethereum.org/raw-loader!-ethersproject-web-lib-index-d-ts.0.23.1.1650320458854.js', 'https://remix.ethereum.org/raw-loader!-ethersproject-wordlists-lib-index-d-ts.0.23.1.1650320458854.js', 'https://remix.ethereum.org/raw-loader!ethers-lib-ethers-d-ts.0.23.1.1650320458854.js', 'https://remix.ethereum.org/raw-loader!ethers-lib-index-d-ts.0.23.1.1650320458854.js', 'https://remix.ethereum.org/raw-loader!web3-bzz-types-index-d-ts.0.23.1.1650320458854.js', 'https://remix.ethereum.org/raw-loader!web3-core-types-index-d-ts.0.23.1.1650320458854.js', 'https://remix.ethereum.org/raw-loader!web3-eth-personal-types-index-d-ts.0.23.1.1650320458854.js', 'https://remix.ethereum.org/raw-loader!web3-eth-types-index-d-ts.0.23.1.1650320458854.js', 'https://remix.ethereum.org/raw-loader!web3-net-types-index-d-ts.0.23.1.1650320458854.js', 'https://remix.ethereum.org/raw-loader!web3-shh-types-index-d-ts.0.23.1.1650320458854.js', 'https://remix.ethereum.org/raw-loader!web3-types-index-d-ts.0.23.1.1650320458854.js', 'https://remix.ethereum.org/raw-loader!web3-utils-types-index-d-ts.0.23.1.1650320458854.js' ]
> 
> files.forEach(f => createScriptTag(f, type))

It is a domain network-related issue while fetching the URL scheme. Turn off the firewall and try the above.

**Comment by Innovoeb** [comment]
Update: as of 4/26/22 Remix IDE (desktop) version 1.3.3 now works without needing to add anything to the console.

**Comment by SalikJamal** [comment]
> 

You're not getting the white screen, I'm still getting it?
![image](https://user-images.githubusercontent.com/52469041/165411500-b34e8691-94a8-471a-b97f-11b48a7d4714.png)

**Comment by SalikJamal** [comment]
> Update: as of 4/26/22 Remix IDE (desktop) version 1.3.3 now works without needing to add anything to the console.

You're not getting the white screen, I'm still getting it?
![image](https://user-images.githubusercontent.com/52469041/165411500-b34e8691-94a8-471a-b97f-11b48a7d4714.png)

**Comment by Innovoeb** [comment]
> > Update: as of 4/26/22 Remix IDE (desktop) version 1.3.3 now works without needing to add anything to the console.
> 
> You're not getting the white screen, I'm still getting it? ![image](https://user-images.githubusercontent.com/52469041/165411500-b34e8691-94a8-471a-b97f-11b48a7d4714.png)

Nope, Remix IDE (desktop) version 0.23.2  now works for me.

**Comment by RFreemanOfHuntEnergy** [comment]
Issue persists in 0.23.3
![image](https://user-images.githubusercontent.com/104995526/166946018-1fcb847f-2dfd-41e5-8497-5f15c5eec37d.png)

**Comment by BourneNeo** [comment]
shit, now I meet it 2, and few days ago, in my another computer i met it and fix it anyway but can't remember how. now meet it again...😣
![image](https://user-images.githubusercontent.com/18527271/167286964-3eab157a-9acd-4bc6-8373-0069cb02c8cb.png)

**Comment by Saigut** [comment]
It's rubbish.

**Comment by Subeesh4020** [comment]
> keep it open - the app is fetching the latest update from the web. It worked after ca 15mins for me :)

It is working

**Comment by yann300** [comment]
The latest release should fix that:
https://github.com/ethereum/remix-desktop/releases
please reopen if the issue is still persisting

**Comment by sicwolf** [comment]
Uninstall Remix Desktop IDE, then install latest version of Remix Destop IDE, the white screen issue could be resolved.
It works well now^_^

**Comment by DieHertz** [comment]
It still persists for me, are there any temporary files I can remove to solve this?

**Comment by krypston104** [comment]
just installed it fresh the latest release (V 1.3.6) and working with it is impossible. It freezes and/or does all kind of freaky stuff while typing. The cursor does not point to where the text is written.

The way it is now, the app is just useless. Has nobody come up with any fix yet?

![Captura de pantalla 2023-04-26 160128](https://user-images.githubusercontent.com/108148253/234600070-9979a37a-a63d-44e7-9e65-afff695ea94a.jpg)

**Comment by MaxPanasenko** [comment]
<img width="1512" alt="Screenshot 2024-01-26 at 13 57 06" src="https://github.com/ethereum/remix-desktop/assets/74506581/53c1411c-1a0b-4582-bd0f-c5f5e73364aa">
still not working. MacOs

**Comment by MochaByte** [comment]
I have the same issue on MacOS, I changed the compiler version from 0.8.22 to 0.8.20 and then it went blank. It works fine when I open it until I choose my current workspace, then all goes white. I can use it for other workspaces though.

**Comment by MaxPanasenko** [comment]
> I have the same issue on MacOS, I changed the compiler version from 0.8.22 to 0.8.20 and then it went blank. It works fine when I open it until I choose my current workspace, then all goes white. I can use it for other workspaces though.

fix this by using -universal.dmg version

**Comment by MochaByte** [comment]
> > I have the same issue on MacOS, I changed the compiler version from 0.8.22 to 0.8.20 and then it went blank. It works fine when I open it until I choose my current workspace, then all goes white. I can use it for other workspaces though.
> 
> I've fix this by using -universal.dmg version

works perfect now! Thanks!
