### ISSUE TITLE
White screen on Remix IDE Mac M1 12.3.1

### ISSUE THREAD

**Issue by K-G-J** [ethereum/remix-desktop#123]
When trying to open the desktop app, I receive a blank white screen.  Was previously working until today (4/18/2022).

<img width="954" alt="Screen Shot 2022-04-18 at 4 32 13 AM" src="https://user-images.githubusercontent.com/91970214/163781452-9112f180-cff8-4210-88a8-776dfc3f1a19.png">

**Comment by jeremyzilar** [comment]
I am getting the same thing 😕

**Comment by amitach** [comment]
I am getting the same

**Comment by jsanders5** [comment]
Same.

**Comment by K-G-J** [comment]
Even when follow guidlines to paste 
```
fetch('https://remix.ethereum.org/assets/version.json', { cache: "no-store" }).then(response => {
  response.text().then(function (data) {
    const version = JSON.parse(data);
    console.log(`Loading Remix ${version.version}`);
    createScriptTag(`polyfills.${version.version}.${version.timestamp}.js`, 'module');
    if (version.mode === 'development') {
      createScriptTag(`vendor.${version.version}.${version.timestamp}.js`, 'module');
      createScriptTag(`runtime.${version.version}.${version.timestamp}.js`, 'module');
    }
    createScriptTag(`main.${version.version}.${version.timestamp}.js`, 'text/javascript');
  });
});
```
I recieve error
<img width="784" alt="Screen Shot 2022-04-18 at 8 29 01 PM" src="https://user-images.githubusercontent.com/91970214/163897341-c06273c6-2b43-446c-862a-26ee09927f6e.png">

**Comment by UltraRareCard** [comment]
same

**Comment by xbladesub** [comment]
same shit

**Comment by paul2234** [comment]
Same

**Comment by paul2234** [comment]
Same. If I let the desktop app sit on the white screen for ~10 minutes (I haven't counted exactly), I get a popup with the following error:

**A JavaScript error occurred in the main process**
Uncaught Exception:
Error: Not connected to the IDE. If you are using a local IDE, make sure to add devMode in client options
at handleConnectionError (/Applications/Remix IDE.app/Contents/Resources/app/node_modules/@remixproject/plugin/lib/client.js:17:11)
at RemixdClient.emit (/Applications/Remix IDE.app/Contents/Resources/app/node_modules/@remixproject/plugin/lib/client.js:116:13)
at FSWatcher.<anonymous> (/Applications/Remix IDE.app/Contents/Resources/app/node_modules/@remix-project/remixd/src/services/

Clicking OK closes the error message. The white screen persists, and the error message will eventually pop up again.

**Comment by jclmnop** [comment]
+1

Same issue, and copy pasting that code snippet into the console doesn't work either.

**Comment by neulishuai** [comment]
same +1
Boring

**Comment by Dou-xx** [comment]
same +1

**Comment by Dou-xx** [comment]
Ubuntu 
![image](https://user-images.githubusercontent.com/26171810/163954184-ea2a197c-b55c-466b-af8f-2a8391047b23.png)

**Comment by filip-alexandrov** [comment]
Probably bad WebSocket. It's on all releases, regardless of the os.

**Comment by Arcuman** [comment]
same

**Comment by hrishibhat** [comment]
same

**Comment by Webber-Woo** [comment]
same, too.
so sad.😣

**Comment by xbladesub** [comment]
actually better to use Neovim or at least VSCode for solidity development

**Comment by thewindear** [comment]
Delete $HOME/.cache_remix_ide the contents from the directory 
Then reopen the app and download remix-project and try

![image](https://user-images.githubusercontent.com/62464025/172830624-18a81c05-afac-4623-bd1c-319ae294445f.png)

**Comment by jodomaq123** [comment]
same white shit screen

**Comment by rgrativol** [comment]
Same in Ubuntu.

**Comment by tonghuitop** [comment]
Same in macOS

**Comment by 0xbepresent** [comment]
Same here

**Comment by wcmoon** [comment]
same

**Comment by sicwolf** [comment]
It is guessed that Remix would load remix-project-0.25.3 with 28.55 MB size from network when starting Remix first time, but the connection is hard to setup successfully, the connection failure caused that Remix raised error "Not connected to the IDE, make sure to add devMode in client options at handleConnectionError".  
My first start also failed with same error, and tried several times, finally, loading 28.55 MB files in my computer consumed at least 30 minutes. Then Remix works well after loading sucessfully.

![RemixLoadingSlowly](https://user-images.githubusercontent.com/7068352/185775295-f93707db-ab74-4eb2-9417-f981fd85acaa.jpg)

**Comment by yruslanluy** [comment]
Same

**Comment by ryestew** [comment]
@yruslanluy, @sicwolf @wcmoon and everyone else:
To get Remix Desktop to load, in the top menu, select **help -> Clear the cache and reload Remix**.
This problem can occur on Remix Desktop after there is a release on Remix IDE.  
NOTE: after the new version is fetched (you'll see a screen with the file being downloaded) there can be delay before Remix Desktop will actually start up. For me this was about a minute delay.


https://user-images.githubusercontent.com/6050001/185831102-451025cc-c22f-415c-9495-5104289cd8cf.mov

**Comment by iznilul** [comment]
same shit

**Comment by denielaa** [comment]
> @yruslanluy, @sicwolf @wcmoon and everyone else: To get Remix Desktop to load, in the top menu, select **help -> Clear the cache and reload Remix**. This problem can occur on Remix Desktop after there is a release on Remix IDE. **NOTE:**after the new version is fetched (you'll see a screen with the file being downloaded), there can be delay before Remix Desktop will actually start up. For me this was about a minute delay. But after that it starts up.
> 
> <img alt="remix-desktop" width="736" src="https://user-images.githubusercontent.com/6050001/185831805-c5608c9b-33d7-4565-928c-8cbc16631a5f.png">

tried this, but still the same

**Comment by thejaspavithran** [comment]
same problem .. macOs 12.5.1

**Comment by yann300** [comment]
The latest release should fix that:
https://github.com/ethereum/remix-desktop/releases
please reopen if the issue is still persisting

**Comment by denielaa** [comment]
> The latest release should fix that: https://github.com/ethereum/remix-desktop/releases please reopen if the issue is still persisting

Yep, confirmed. it is working
awesome

**Comment by DanielZSY** [comment]
![image](https://user-images.githubusercontent.com/84162682/205918544-84eef1de-4894-4497-99f4-f8760063373c.png)
error

**Comment by bd100b** [comment]
Macbook m1
Macos: Ventura 13.0 (22A380)
Remix 0.29.0
White screen after saving the smart contract

**Comment by amirhosseinNouri** [comment]
> https://github.com/ethereum/remix-desktop/releases

This works. Thanks.

**Comment by parsanoori** [comment]
Macbook pro 2021 M1 pro
MacOS: Ventura 13.0.1
Remix release v1.3.6
White screen after compiling solidity file.

**Comment by joeizang** [comment]
> Macbook pro 2021 M1 pro MacOS: Ventura 13.0.1 Remix release v1.3.6 White screen after compiling solidity file.

I have ventura 13.1 I can confirm that remix desktop is working fine. See image below:
<img width="1420" alt="Screenshot 2023-01-23 at 12 16 54" src="https://user-images.githubusercontent.com/4255962/214027062-818e8123-d90c-4774-8443-045d8783660a.png">

Can you confirm what contract it is you are compiling? You could also check the console for any specific errors. I will be glad to help anyway I can

**Comment by emclab** [comment]
same with 0.29.2 on M1 monterey

**Comment by joeizang** [comment]
> same with 1.3.6.1000 on M1 monterey

@emclab can you give some more details about your issue?
