### ISSUE TITLE
White screen on Remix IDE  Ubuntu Linux 20.04

### ISSUE THREAD

**Issue by franck2019** [ethereum/remix-desktop#124]
![image](https://user-images.githubusercontent.com/43989941/163813149-6ed10995-37a8-4d6f-b535-a394ab0223b6.png)

**Comment by franck2019** [comment]
How can I resolve it?

For now I just want to retrieve the directory I created with the ide.
Where does the remix IDE Desktop save all filles and/or directory

**Comment by muturgan** [comment]
same problem

**Comment by Henry-Freck** [comment]
Same problem

**Comment by generall3** [comment]
Same problem, just blank image

**Comment by adriadrop** [comment]
Same thing :(

**Comment by adriadrop** [comment]
Tried also previous version, same thing happens.

**Comment by rickbeeloo** [comment]
Same here :(

**Comment by yann300** [comment]
The latest release should fix that:
https://github.com/ethereum/remix-desktop/releases
please reopen if the issue is still persisting
