### ISSUE TITLE
Remix mac Desktop version 0.23.1 Cannot run and Failed to import JS package 

### ISSUE THREAD

**Issue by Clothing999** [ethereum/remix-desktop#125]
How can I fix it？
<img width="800" alt="image" src="https://user-images.githubusercontent.com/90775104/163942187-5dbb4abe-f0d1-47b1-a2fd-3df97ac0f174.png">

**Comment by 18186877435** [comment]
Who can help me？

**Comment by banwang811** [comment]
god bless you

**Comment by dhood** [comment]
others are having this issue too, see https://github.com/ethereum/remix-desktop/issues/122#issuecomment-1106260954 for some tips

**Comment by Clothing999** [comment]
> 其他人也有这个问题，请参阅[#122（评论）](https://github.com/ethereum/remix-desktop/issues/122#issuecomment-1106260954)以获取一些提示

Thank you for your help
