### ISSUE TITLE
 A JavaScript error occurred in the main process #127

### ISSUE THREAD

**Issue by bigapple999** [ethereum/remix-desktop#127]
When opening, with the issue as in below. Can anyone know how to add a devMode?  
![图片](https://user-images.githubusercontent.com/102247322/164874606-1e601520-29c3-461c-97d4-9c97dd7d2790.png)

**Comment by MiraDave247** [comment]
I solved this yesterday by just connecting to Internet before I load the app I'm using Win 7, try that.
