### ISSUE TITLE
Desktop app doesn't launch on Ubuntu 22.04

### ISSUE THREAD

**Issue by pavluha2dva8** [ethereum/remix-desktop#137]
The application screen appears for a second and immediately closes.

![Screenshot from 2022-06-30 13-52-21](https://user-images.githubusercontent.com/70954883/176660250-9ce05419-def7-4042-8ac2-8ba740eca9e8.png)

**Comment by eathom91** [comment]
Can confirm, same issue on 22.04

**Comment by yann300** [comment]
The latest release should fix that:
https://github.com/ethereum/remix-desktop/releases
please reopen if the issue is still persisting
