### ISSUE TITLE
A JavaScript error occurred in the main process on mac m1

### ISSUE THREAD

**Issue by Saibejjani** [ethereum/remix-desktop#138]
<img width="632" alt="Screenshot 2022-07-06 at 1 11 17 PM" src="https://user-images.githubusercontent.com/64737059/177497364-7e918f71-bd4c-47ee-8be2-75e9fea3ab87.png">

I am unable to launch remix on mac m1 using desktop app.

**Comment by TheStarBoys** [comment]
I'm with a same issue too.

**Comment by yann300** [comment]
latest release should fix that (please use the universal build if you have an arm64 mac):
https://github.com/ethereum/remix-desktop/releases
please reopen if the issue persists

**Comment by lollipop190** [comment]
hi, i've download the latest versin but i still have the same problem when opening(the error message is also the same). But i am now using MacOs 13, is it the reason?

**Comment by tuanhv-0694** [comment]
I have similar problem. I'm using macOS Ventura also

**Comment by mtrussell** [comment]
I'm using MacOS Ventura 13.0.1, and I'm also getting this error.
