### ISSUE TITLE
Desktop app cant lunch on mac m1 version 1.33

### ISSUE THREAD

**Issue by henrY2Young** [ethereum/remix-desktop#140]
![image](https://user-images.githubusercontent.com/13415082/179168144-2c21432c-b2d4-431c-8828-6ff8680673c0.png)

**Comment by winterlightning** [comment]
I think I also have this issue, just that message and a blank screen after

**Comment by staminna** [comment]
In my case it doesn't even open MacOS Monterey 12.4. It is the second download.
Macbook M1 Pro.
By executing it gives popup error straight away.

**Comment by rishu605** [comment]
Update to v1.34

**Comment by YuntianCheng** [comment]
> Update to v1.34

v1.34 has the same issue
<img width="801" alt="image" src="https://user-images.githubusercontent.com/29092622/183011554-c81924ed-16b5-450f-98ce-800c904bfdc3.png">

**Comment by staminna** [comment]
True

A sexta, 5/08/2022, 07:01, YuntianCheng ***@***.***> escreveu:

**Comment by yann300** [comment]
The latest release should fix that (please use the universal build if you have an arm64 mac):
https://github.com/ethereum/remix-desktop/releases
