### ISSUE TITLE
Remix desktop is Not responding.

### ISSUE THREAD

**Issue by Zartaj0** [ethereum/remix-desktop#154]
The remix desktop app was running before the update.
After I updated the app it is not responding anymore.
![Screenshot (53)](https://user-images.githubusercontent.com/91191500/181874436-95692106-1edb-470d-9e0e-b7022eb0e095.png)
Solve this please.

**Comment by ertra** [comment]
Happened to me as well, but restarting the app solved the problem (the app was downloading the new content).

**Comment by yann300** [comment]
The latest release should fix that:
https://github.com/ethereum/remix-desktop/releases
please reopen if the issue is still persisting

**Comment by Zartaj0** [comment]
I am not using remix desktop since that time. I lost each file that was there on the remix desktop. Don't trust no more. 
Now I write code on the browser and save those files in my local storage.

**Comment by ertra** [comment]
> I am not using remix desktop since that time. I lost each file that was there on the remix desktop. Don't trust no more. Now I write code on the browser and save those files in my local storage.

the new version now throws some JavaScript exceptions on the startup :-( , I also use browser version more often.
