### ISSUE TITLE
Support native Apple silicon 

### ISSUE THREAD

**Issue by arcc1845** [ethereum/remix-desktop#156]
Now, we have to run the remix-desktop using Rosetta 2.

It is expected that will need to upgrade `electron` to version 11 or higher.

**Comment by adewumiadedeji** [comment]
I make a fix to this by updating macos-release version to 3.1.0 in source package.json file. This new macos-release version has support for Monterey and Ventura IOS versions.

**Comment by yann300** [comment]
latest release should fix that (please use the universal build if you have an arm64 mac):
https://github.com/ethereum/remix-desktop/releases
