### ISSUE TITLE
a javascripte error occered in the main process on macbookair m1 MacOS 13

### ISSUE THREAD

**Issue by lollipop190** [ethereum/remix-desktop#166]
<img width="496" alt="截屏2022-09-20 下午4 51 27" src="https://user-images.githubusercontent.com/58462846/191213569-92c81dfb-b1b1-4ba2-8b38-e2f6fa34a4ca.png">

the error message is as above.
the remix version is the latest.
and macos version is 13 beta.
(if this macos versino were not supported , i could fully understand. thank u.

**Comment by lollipop190** [comment]
> 

i am sorry, there seems to be a missing of link?

**Comment by ToDestiny** [comment]
Same error. Any fix?

**Comment by G33kNoob** [comment]
get error too
on M1 ventura

**Comment by somenkovnikita** [comment]
same issue, M1 Pro, macOS 13.0 (22A380)

**Comment by jerdys** [comment]
Same problem on Intel Macbook Pro, any ETA of the fix?

**Comment by mangesh-singh** [comment]
is there any update on the fix?

**Comment by alexincrypto** [comment]
Did anyone understand how to use https://github.com/ethereum/remix-desktop/pull/98 ?

This java issue drives me mad...

**Comment by Saszr** [comment]
I made minor fixes and build the temporary package.

https://github.com/Saszr/remix-desktop/releases/tag/v1.3.5-temp

**Comment by mangesh-singh** [comment]
> I made minor fixes and build the temporary package.
> 
> https://github.com/Saszr/remix-desktop/releases/tag/v1.3.5-temp

thanks bro..working on M1 ventura

**Comment by szhumadildin** [comment]
> I made minor fixes and build the temporary package.
> 
> https://github.com/Saszr/remix-desktop/releases/tag/v1.3.5-temp

Thanks M1 working!!!!

**Comment by amirhosseinNouri** [comment]
> I made minor fixes and build the temporary package.
> 
> https://github.com/Saszr/remix-desktop/releases/tag/v1.3.5-temp

This works. Thanks

**Comment by nerr** [comment]
Same problem

**Comment by mtrussell** [comment]
I have the same issue.

I'm using:
MacOS Ventura 13.0.1
M1 chip

**Comment by yann300** [comment]
sorry for the huge delay, please install the latest release : https://github.com/ethereum/remix-desktop/releases
