### ISSUE TITLE
When I try to run Remix Desktop from a DMG install I get a "not trusted software" error

### ISSUE THREAD

**Issue by reselbob** [ethereum/remix-desktop#176]
Then my Mac won't open it. I can cancel or send it to trash.

I am running a Mac Mini M1,  MacOS Monterey 12.5.1.

Help?

**Comment by yann300** [comment]
There should be a way in the preference to allow running it. please check https://support.apple.com/guide/mac-help/open-a-mac-app-from-an-unidentified-developer-mh40616/mac
