### ISSUE TITLE
An explanation screen before selecting sync folder at startup

### ISSUE THREAD

**Issue by Aniket-Engg** [ethereum/remix-desktop#2]
Currently as soon as one clicks on the application icon, it goes to select a directory and opens file explorer. This doesn't give any idea of purpose for which directory is getting selected.  Also, if you click 'cancel' on select your directory dialog, it automatically selects the current selected folder in the dialog. Ideal way can be closing the application with an error/warning or it can be discussed to make it better.

A screen can be added at startup which explains the purpose and then go to choose the directory.

Version: v1.0.3-beta.5
OS: Ubuntu 16.04

**Comment by TobiWo** [comment]
This probably refers to the problem I'm currently facing to start Remix at all. I have no idea which kind of folder I should open as a working directory. Currently no matter which folder I choose I only get the window of the Electron App Manager. It would be really helpful to explain anywhere (maybe in the github ReadMe) how to start the application correctly.

Version: v1.0.3-beta.5 / v1.0.3-beta.6 
OS: Windows 10

**Comment by yann300** [comment]
Now you should be able to click on the menu `Files/Open Folder` for browsing the folder in the file explorer.
