### ISSUE TITLE
Bothersome tool tips

### ISSUE THREAD

**Issue by zach-is-my-name** [ethereum/remix-desktop#22]
Tool tips in Plugin Manager are redundant and do not seem necessary. 

Same with tool tips in File Explorer, they do add the file path, but the path is already referenced in the visual file tree - so they seem unnecessary as well.     

Version 1.08 (linux)

**Comment by yann300** [comment]
we are currently doing an important refactoring of the UI and this should be fixed hopefully soon.
Thanks and sry for the late reply
