### ISSUE TITLE
Deploying contract with Ganache always ask for ”Passphrase requested" 

### ISSUE THREAD

**Issue by ldru** [ethereum/remix-desktop#23]
1、Connected to Ganache by  selecting “Web3 Provider” with the parameter "http://127.0.0.1:7545"
2、Deploy the contract，then a window is prompted with the title ”Passphrase requested"  and asking for  "Personal mode is enabled. Please provide passphrase of account". 
 But Ganache does not have passphrase !!!

**Comment by yann300** [comment]
do you have "personal mode" activated in the settings of Remix IDE? if so could you try to deactivate it?
