### ISSUE TITLE
How to connect explorer's MetaMask??

### ISSUE THREAD

**Issue by boy-good** [ethereum/remix-desktop#28]
Error: No injected Web3 provider found. Make sure your provider (e.g. MetaMask) is active and running (when recently activated you may have to reload the page).

**Comment by yann300** [comment]
well the thing is that for the moment this is not possible, but you can use wallet connect plugin (to connect to your mobile wallet). Metamask has a mobile wallet as well.

**Comment by boy-good** [comment]
> well the thing is that for the moment this is not possible, but you can use wallet connect plugin (to connect to your mobile wallet). Metamask has a mobile wallet as well.

ok Thanks,
