### ISSUE TITLE
v1.0.8 does not work on the win10

### ISSUE THREAD

**Issue by little-petrol** [ethereum/remix-desktop#36]
Remix-IDE-Setup-1.0.8.exe and Remix-IDE-1.0.8-win.zip
I can open an application window, but nothing appear while I click "Open Folder"

**Comment by yann300** [comment]
This should be fixed, please get the latest version https://github.com/ethereum/remix-desktop/releases .
I am closing the issue but feel free to reopen if it is still not working.
