### ISSUE TITLE
In Linux Mint App can not start

### ISSUE THREAD

**Issue by AVert** [ethereum/remix-desktop#38]
Linux Mint App can not start

./Remix-IDE-1.1.0.AppImage 
running 1.1.0
[@octokit/rest] `const Octokit = require("@octokit/rest")` is deprecated. Use `const { Octokit } = require("@octokit/rest")` instead
start shared folder service
Sun Feb 07 2021 01:51:17 GMT+0300 (Moscow Standard Time) remixd is listening on 127.0.0.1:65520
Sun Feb 07 2021 01:51:17 GMT+0300 (Moscow Standard Time) remixd is listening on 127.0.0.1:65521
generating 2048-bit (rsa only) RSA keypair...
/tmp/.mount_Remix-jn5JFq/remix-ide: symbol lookup error: /tmp/.mount_Remix-jn5JFq/resources/app/node_modules/ursa-optional/build/Release/ursaNative.node: undefined symbol: BN_new

installed with package silently fall

**Comment by toonsevrin** [comment]
same on ubuntu

**Comment by krypdkat** [comment]
confirm the same issue on Ubuntu 20 for both .deb and .AppImage

**Comment by matiyin** [comment]
can confirm the same, 1.1 not starting, 1.0.8 is works.
Linux Mint 20

**Comment by pcfreak30** [comment]
I can confirm as well. the app image and deb on linux mint MATE 20 are broken. 1.0.8 runs but the UI is white and unusable (CSS issues?).

1.0.7 works fine.

**Comment by angelcervera** [comment]
Duplicate issue #40

**Comment by GhengisWim** [comment]
same linux mint 20.1. it just blinks out.     can't GitSome it, debian  package doesnt work, no worries the browserapp is good

**Comment by yann300** [comment]
The last release should fix the issue https://github.com/ethereum/remix-desktop/releases 
Thanks for your patience. I'll close this issue, feel free to reopen it if needed.
