### ISSUE TITLE
Remixd doesn't work on windows OS

### ISSUE THREAD

**Issue by RomanG11** [ethereum/remix-desktop#39]
Remixd connected to remix instance but shows empty directory

**Comment by susengo** [comment]
I had the same problem on MacOS.

**Comment by yann300** [comment]
@RomanG11 @susengo do you still have this issue with the latest release?

**Comment by yann300** [comment]
the latest release should fix that - https://github.com/ethereum/remix-desktop/releases - sorry for the delay.
Please make sure to reopen if the issue persists.
