### ISSUE TITLE
Cannot start remix-ide - ursaNative.node: undefined symbol: BN_new

### ISSUE THREAD

**Issue by d-sfounis** [ethereum/remix-desktop#40]
Hey, is there something wrong in the latest release? I could start it just fine yesterday, but today every time I try to launch remix-ide I get: 

```
running 1.1.0
[@octokit/rest] `const Octokit = require("@octokit/rest")` is deprecated. Use `const { Octokit } = require("@octokit/rest")` instead
start shared folder service
Sat Mar 06 2021 20:29:31 GMT+0200 (Eastern European Standard Time) remixd is listening on 127.0.0.1:65520
Sat Mar 06 2021 20:29:31 GMT+0200 (Eastern European Standard Time) remixd is listening on 127.0.0.1:65521
generating 2048-bit (rsa only) RSA keypair...
/opt/Remix IDE/remix-ide: symbol lookup error: /opt/Remix IDE/resources/app/node_modules/ursa-optional/build/Release/ursaNative.node: undefined symbol: BN_new
```
Did something break with OpenSSL?

**Comment by TheoThug** [comment]
Any update on this issue? Lost a bunch of my saved work from last browser edition update so trying to use desktop but encountering this issue as well. (Ubuntu Focal)

**Comment by cesar-lp** [comment]
Hi, any update on this one? I just downloaded the the .deb file, installed it and the same error popped up

**Comment by d-sfounis** [comment]
Yeah no luck so far, seems like something broke inside their huge npm
dependency tree.

I just ended up using Truffle

Dimitris Sfounis

Co-founder & Software Engineer @ Bluechain SCE, EU
Student of Computer Science, Aristotle University of Thessaloniki
https://bluechain.tech
https://dsfounis.com

**Comment by SinglePageBookProject** [comment]
Same problem here. I just installed latest version.

It looks, somewhere it's not linking against libssl.so (openssl 1.1)

I checked that I have it installed on my system and that BN_new is defined in the library.
  ```
  $ nm -gD /usr/lib/x86_64-linux-gnu/libssl.so.1.1 | grep BN_new
           U BN_new
```
 
But remix-ide binary ignore the library:
  ```
  ldd remix-ide | grep libssl
  (empty)
```
I was expecting something similar to:
 ```
  $ ldd /usr/bin/openssl | grep libssl
	libssl.so.1.1 => /usr/lib/x86_64-linux-gnu/libssl.so.1.1 (0x00007f8bcd998000)
```
```

**Comment by angelcervera** [comment]
Same issue with the newest version 1.2.0
Tested remix-ide_1.2.0_amd64.deb and Remix-IDE-1.2.0.AppImage

**Comment by taxmeifyoucan** [comment]
Same issue on Debian Buster and Ubuntu 21.04, deb package and Appimage comes with the same error.

**Comment by bradmurmz** [comment]
To fix you just need to run "npm install" inside the node_modules/ursa-optional/ directory, and then delete the build folder located there. Upon next launch It falls back to using the scripts instead of the pre-compiled binary, so it should just start right up.

If you are using the AppImage, you'll need to run ./Remix-IDE-1.2.0.AppImage --appimage-extract first and then go into the squashfs-root/resources/app/node_modules/ursa-optional/ and complete the previous step

if you want to repackage the AppImage, you can use appimagetool ( separate program ) and run "appimagetool -v ./squashfs-root/" otherwise just run ./AppRun ( inside the squash-fs/ folder )

**Comment by fantauzzi** [comment]
Following @bradmurmz 's instructions for the AppImage I have been able to run Remix and compile a contract (Ubuntu 20.04).

**Comment by yann300** [comment]
The last release should fix the issue https://github.com/ethereum/remix-desktop/releases 
Thanks for your patience. I'll close this issue, feel free to reopen it if needed.
