### ISSUE TITLE
"You do not have permission to open the application" on M1 with macOS Big Sur

### ISSUE THREAD

**Issue by dvcrn** [ethereum/remix-desktop#42]
Getting the following error when trying to run the latest release: 

<img width="372" alt="Screen Shot 2021-03-09 at 17 53 48" src="https://user-images.githubusercontent.com/688326/110444488-6c2fff00-8100-11eb-8bdd-3b41ea753ea8.png">

Tried the usual culprits without luck:

```
sudo xattr -dr com.apple.quarantine Remix\ IDE.app
sudo chmod -R 755 Remix\ IDE.app
```

System is macOS 11.2.2 Big Sur on M1 chip

**Comment by fzxu** [comment]
I found a solution. You need to download the DMG file and open it. Don't move to trash on the first opening. Go to system setting -> security & privacy, allow the open there. You should be able to open it.

**Comment by LkingForW** [comment]
Another solution is to find 'Remix IDE" on the Application finder and control click open. This will promt you with a warning regarding the authorized developer. You can click "open anyway" and the machine will automatically open this in the future. Just double click and fire away ! 🚀

**Comment by yann300** [comment]
Closing this issue. 
@dvcrn please reopen it, if this is still not working for you.

**Comment by dingshukai** [comment]
For big sur user, Do not download mac.zip, but .dmg

**Comment by vagman** [comment]
For macOS Monterey, .dmg file was working fine too, after installation. Make sure you follow @LkingForW 's steps because just by clicking it, it won't open.

**Comment by YarikSTND** [comment]
> I am getting java error when open remix ide

Me to the error is "A javaScript error occurred in the main process", didn't find how to solve it
