### ISSUE TITLE
remix-desktop FILE EXPLORERS is Empty

### ISSUE THREAD

**Issue by snwokenk** [ethereum/remix-desktop#45]
The File explorer tab is empty. Nothing is displayed, not the sample contracts section or the localhost. reinstalled remx-desktop, restarted laptop. Still getting the same issue.

**Comment by snwokenk** [comment]
The work around provided here https://github.com/ethereum/remix-desktop/issues/31 , solved the issue.

**Comment by bbhart** [comment]
Encountered same problem on Windows. No workspaces, and clicking New File on the right didn't do anything.
![explorer-empty](https://user-images.githubusercontent.com/474498/113871023-746f6e80-9780-11eb-8464-8a33a475f14e.jpg)

Uninstall/reinstall didn't help. Deleting %APPDATA%\remix-ide corrected the issue.

**Comment by yann300** [comment]
we had some issues with the workspace manager some months ago. everything should be back to normal now.
I'll close the issue, please reopen if needed
