### ISSUE TITLE
Unable to interact with smart contract using ABI

### ISSUE THREAD

**Issue by KohliSuraj** [ethereum/remix-desktop#49]
Using the latest version of remix at https://remix.ethereum.org/.

I am unable to interact with a smart contract deployed on ropsten network using it's ABI. Under the "Deploy & Run Transactions" section, the "At Address" button is always disabled.

I checked at https://github.com/ethereum/remix-desktop/releases/, the version 1.1.0 is the one I am facing an issue with.

I am able to make the same contract ABI work on Remix IDE on Mac OS by using version 1.0.7.

**Comment by yann300** [comment]
This should be fixed, I'll close the issue, please reopen it if needed.
