### ISSUE TITLE
MacOS release broken

### ISSUE THREAD

**Issue by mickys** [ethereum/remix-desktop#55]
![Screenshot 2021-06-14 at 02 32 46](https://user-images.githubusercontent.com/200507/121825032-d4225280-ccb8-11eb-8046-439902c7f11e.png)

**Comment by mickys** [comment]
yup, that's because of the mac zip, dmg is fine

**Comment by yann300** [comment]
ok thanks, we probably shouldn't propose this zip to download

**Comment by yann300** [comment]
the latest release should fix that - https://github.com/ethereum/remix-desktop/releases - sorry for the delay.
Please make sure to reopen if the issue persists.
