### ISSUE TITLE
MacOS 12 Monterey (beta 2 + 3) error at startup

### ISSUE THREAD

**Issue by codeoffconduct** [ethereum/remix-desktop#61]
On the MacOS Monterey, Remix does not work. Error attached
<img width="256" alt="Screenshot 2021-07-15 at 16 45 22" src="https://user-images.githubusercontent.com/59344690/125772039-9493722c-fe4f-4e9e-89d6-9aa0e07afaa3.png">

**Comment by alfatetan** [comment]
The same problem. IDE shows a message "Connection to remixd terminated.Please make sure remixd is still running in the background." after running.

**Comment by sw-11-00** [comment]
I'm a Mac m1 system and still have the same problem

**Comment by yann300** [comment]
which build did you install from https://github.com/ethereum/remix-desktop/releases ?
can you try the `inversal` one

**Comment by sw-11-00** [comment]
I've tried multiple versions, including the universal one and some other Macs that work, and still have the same problem.
My Mac version is the latest 13.0, Ventura

**Comment by stunter777** [comment]
> I've tried multiple versions, including the universal one and some other Macs that work, and still have the same problem. My Mac version is the latest 13.0, Ventura

Same with me!
