### ISSUE TITLE
MacOS - v1.2.1 - Update issues - Please give us an option to turn automatic update checks OFF

### ISSUE THREAD

**Issue by mickys** [ethereum/remix-desktop#62]
While Running v1.2.1 on Catalina the app keeps checking for an update which if i cancel, 5 minutes later pops up again.

![Screenshot 2021-07-20 at 06 09 17](https://user-images.githubusercontent.com/200507/126256076-806f6177-1b5a-488d-aa59-9187de1a4e59.png)

If i accept the update, it just fails

![Screenshot 2021-07-20 at 06 09 09](https://user-images.githubusercontent.com/200507/126256080-d1e5dc7b-9e38-4b45-85d8-febed35bb1f1.png)

Please give us an option to turn automatic update checks OFF.

For now i've just blocked the thing in my firewall.. by denying it access to github-releases.githubusercontent.com

**Comment by yann300** [comment]
this should be deactivated now
