### ISSUE TITLE
Hardhat compilation not working

### ISSUE THREAD

**Issue by yann300** [ethereum/remix-desktop#67]
in remix-project we trigger a recheck of the current folder to detect if it's hardhat or not when `setworkspace ` is triggerred.
see https://github.com/ethereum/remix-project/blob/71633c513b8eb2141b207baf300f6a35b2823632/apps/remix-ide/src/app/tabs/compile-tab.js#L120

The issue is that in the case of remix-desktop, it is possible to change the folder using `Open Folder` menu option and in that case, the `setworkspace ` doesn't get trigerred (which is expected)

**Comment by bunsenstraat** [comment]
You mean setworkspace event
