### ISSUE TITLE
Background update fails on MacOS 11.5.2

### ISSUE THREAD

**Issue by bbeale** [ethereum/remix-desktop#76]
Remix Desktop Version: 1.3.1

Clicking through the update popup...
![Screen Shot 2021-09-05 at 7 29 32 AM](https://user-images.githubusercontent.com/9686813/132125184-997535b2-9381-40ac-a685-1151b78a3ada.png)

Triggers an error message
![Screen Shot 2021-09-05 at 7 30 00 AM](https://user-images.githubusercontent.com/9686813/132125185-3219dc5c-2990-4081-a2c9-767ac7962dfc.png)

Also had the same issue upgrading from 1.3.0 to 1.3.1, which I got around it by re-downloading the dmg file from GitHub.

**Comment by yann300** [comment]
sorry for the late answer, could you update to 1.3.2? thanks

**Comment by bbeale** [comment]
No worries. That update actually did work for me back when I saw that it became available. I actually have some other unrelated issues with it at the moment, but I'll close this issue.
