### ISSUE TITLE
Unable to open Remix IDE on macOS

### ISSUE THREAD

**Issue by namannarula** [ethereum/remix-desktop#85]
Remix IDE won't open on my machine, it just spits out this error.
<img width="372" alt="Screenshot 2021-10-31 at 13 27 16" src="https://user-images.githubusercontent.com/44409513/139573739-4b82bbf5-6d46-4b6c-8eff-e0589558a8cd.png">

Device Details:
MacBook Pro (13-inch, M1, 2020)
macOS Monterey 12.0.1

**Comment by nazrdogan** [comment]
same issue

**Comment by MichaelFriedrich** [comment]
Same here on Monterey macOS 12.0.1

**Comment by SteveBacci** [comment]
Same here

**Comment by wheeeper** [comment]
> Maybe same as [this](https://stackoverflow.com/questions/68318289/ionic-fails-building-in-macos-12-monterey) issue.

I think this is definitely the cause. The package `os_name` has dependency on `macos-release`. `yarn update` fixes the issue for me. You can then generate the dmg through `yarn dist`

**Comment by OumArEtH** [comment]
I edited the index.js file in `/Applications/Remix IDE.app/Contents/Resources/app/node_modules/macos-release` and added `[21, ['Monterey', '12']]` in the `nameMap` and it worked!

**Comment by SteveBacci** [comment]
Worked for me

**Comment by hkkhuang** [comment]
Same here on MacOS Big Sur 11.6

**Comment by jedidefault** [comment]
> I edited the index.js file in `/Applications/Remix IDE.app/Contents/Resources/app/node_modules/macos-release` and added `[21, ['Monterey', '12']]` in the `nameMap` and it worked!

Problem solved! Thanks!
