### ISSUE TITLE
The versions after 1.3.0 in ubuntu  have no deploy button??

### ISSUE THREAD

**Issue by KenHopkin** [ethereum/remix-desktop#89]
The versions after 1.3.0 in ubuntu  have no deploy button?? I can not find that in the ui and plugin

**Comment by KenHopkin** [comment]
I have download and test 1.3.0.deb and 1.3.1, 1.3.2, all of them have no Deploy or Run button

**Comment by yann300** [comment]
you should have it.
Do you mean you don't see to the deploy tab (side panel) or that you see the deploy tab but you can't actually deploy a contract?

**Comment by KenHopkin** [comment]
I mean I can't see the deploy tab(side panel)
![image](https://user-images.githubusercontent.com/35953970/142133794-e0ad6a9d-6000-4a53-b69a-52398f2cdc80.png)


> you should have it. Do you mean you don't see to the deploy tab (side panel) or that you see the deploy tab but you can't actually deploy a contract?

**Comment by yann300** [comment]
We are tracking this issue since a while, but couldn't really reproduce it.
Could you open the developer tools and post the errors here?
To fix this you could either:
 - go in the plugin manager (the plug icon) and activate run and deploy manually.
 - or remove the key "workspace" from the local storage (that you can access through the developer tools).

**Comment by KenHopkin** [comment]
I can't find "run and deploy" in the plugin manager. ( I search it, but I can't find it)
![image](https://user-images.githubusercontent.com/35953970/142349117-2324880e-5d82-4490-bac4-173e396500c3.png)
The errors are as follows, is anything wrong?
![image](https://user-images.githubusercontent.com/35953970/142349292-9ff02ad7-2fe3-4f46-ab7b-e2a1fc3a9bc3.png)

**Comment by yann300** [comment]
oh ok I see, so can you try the second solution:
 - remove the key "workspace" from the local storage (that you can access through the developer tools).

**Comment by KenHopkin** [comment]
> oh ok I see, so can you try the second solution:
> 
> * remove the key "workspace" from the local storage (that you can access through the developer tools).

Do you mean deleting this? I had deleted it but I still can't see the deploy tab(side panel)

![image](https://user-images.githubusercontent.com/35953970/142587034-19b29686-7925-4dac-a243-3e3179453d4c.png)
![image](https://user-images.githubusercontent.com/35953970/142587413-1e6c6471-8747-4919-92b3-964cb12ad1de.png)

**Comment by yann300** [comment]
I mean this, you can open the developer tools in the menu `Help`
![remix](https://user-images.githubusercontent.com/6940742/142839261-b58e8448-6dc8-4a19-83eb-603e093a9e52.png)

**Comment by KenHopkin** [comment]
> I mean this, you can open the developer tools in the menu `Help` ![remix](https://user-images.githubusercontent.com/6940742/142839261-b58e8448-6dc8-4a19-83eb-603e093a9e52.png)

Oh, thanks! I have removed the key "workspace" from the local storage, and after I restart remix-ide, the deploy tab (side panel) shows up!
![image](https://user-images.githubusercontent.com/35953970/142848230-228918ae-1b8c-4cab-8fa0-08f1ea581a71.png)

**Comment by yann300** [comment]
ok great, if you see the issue again, could you send us the content of the terminal, I'd like to check the javascript errors?
thanks.
Let's keep the issue opened

**Comment by KenHopkin** [comment]
> ok great, if you see the issue again, could you send us the content of the terminal, I'd like to check the javascript errors? thanks. Let's keep the issue opened

ok, I will.

**Comment by yann300** [comment]
the latest release should fix that - https://github.com/ethereum/remix-desktop/releases - sorry for the delay.
Please make sure to reopen if the issue persists.
