### ISSUE TITLE
White window on windows desktop

### ISSUE THREAD

**Issue by stranger-games** [ethereum/remix-desktop#91]
Hi,

Here's what I get with a fresh remix installation on windows. White window loading indefinitely.

![image](https://user-images.githubusercontent.com/7149867/141981022-b0e7b27d-234d-412b-aa3b-fc3e85c715b9.png)

Thank you for advance.

**Comment by hippiemeraki** [comment]
I also face the same issue are you using windows 11?

**Comment by Diagileva** [comment]
the same.. Did you manage to fix it?

**Comment by topwebguru7** [comment]
Same. I hope you can solve it soon

**Comment by yarg-eth** [comment]
Bruuuh, same thing is happening to me

**Comment by expressd3v** [comment]
same issue here

**Comment by yarg-eth** [comment]
> same issue here

Remix trying to make me use a browser based IDE🤮, an absolute command line expert, or trying to make me create a GUI everytime I want to interact with my contract.
![image](https://user-images.githubusercontent.com/29768100/163497367-0d5d4c01-32a0-46b1-8609-e257f9562ef8.gif)

**Comment by yann300** [comment]
the latest release should fix that - https://github.com/ethereum/remix-desktop/releases - sorry for the delay.
Please make sure to reopen if the issue persists.
