### ISSUE TITLE
Cannot open in macOS Big Sur

### ISSUE THREAD

**Issue by vpier** [ethereum/remix-desktop#92]
Gives always an error that developer is not verified. Tried all options like open anyway in security settings, control-click open however without any luck.

Version 1.3.2

**Comment by NewOldGeek** [comment]
Edit security to allow it anyway though it has non stop JS error and won't run in any event

**Comment by DaC1989** [comment]
I have the same problem

**Comment by IlyaUmanets** [comment]
Try download `.dmg` file - Remix-IDE-1.3.3.dmg. Remix-IDE-1.3.3-mac.zip didn't work for me neither. It said "It can't be opened"

**Comment by yann300** [comment]
the latest release should fix that - https://github.com/ethereum/remix-desktop/releases - sorry for the delay.
Please make sure to reopen if the issue persists.
