### ISSUE TITLE
Remix Desktop not loading file content - macOS Monterey

### ISSUE THREAD

**Issue by RamaDL** [ethereum/remix-desktop#94]
Remix Desktop on MacOS Monterey is not showing files content. Code edit section stuck in "Loading..."

<img width="1064" alt="Captura de Pantalla 2021-11-28 a la(s) 22 46 46" src="https://user-images.githubusercontent.com/14312092/143796548-f1004100-5597-4798-ae50-fa1400d3defe.png">

**Comment by NaveganteX** [comment]
I am having the exact same issue. And it has been going on for two days. Remix Desktop on macOS Catalina in my case.  Code edit section stuck forever in "Loading..
<img width="1120" alt="Screen Shot 2021-11-28 at 23 10 51" src="https://user-images.githubusercontent.com/48041586/143798198-093ed968-0fe2-4738-a438-778349befc40.png">
."

**Comment by yann300** [comment]
the latest release should fix that - https://github.com/ethereum/remix-desktop/releases - sorry for the delay.
Please make sure to reopen if the issue persists.
