### ISSUE TITLE
Remix Desktop not loading file content - macOS Catalina

### ISSUE THREAD

**Issue by NaveganteX** [ethereum/remix-desktop#95]
I am having  an issue. And it has been going on for two days now. Remix Desktop on macOS Catalina in my case. Code edit section stuck forever in "Loading... Please, fix it ASAP.
<img width="1120" alt="Screen Shot 2021-11-28 at 23 10 51" src="https://user-images.githubusercontent.com/48041586/143798295-cfc56f7c-42c0-41f6-88be-4df3ce4dbf31.png">

**Comment by jayhill365** [comment]
im facing the same issue here as well, files won't load

**Comment by aakh1361** [comment]
me too
Today I wanted to try the code and I had the same problem
